version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - rust-api-pgdata:/var/lib/postgresql/data/
volumes:
  rust-api-pgdata: {}
